### ISSUE TITLE
Add libraries

### ISSUE THREAD

**Issue by shawtymon** [QeaML/ximfect#3]
Add a way to install libraries into ximfect which would be usable inside effects.

Perhaps called 'extensions' structured like effects but stored in APPDATA/ximfect/extensions.

All the library would be stored in different files, which all would be loaded automatically.

Example script (not perfect):
```
function _removeRed(pixel) {
    return { r: 0, g: pixel.g, b: pixel.b, a: pixel.a };
}

var MODULE = {
    removeRed: _removeRed
}
```

Example metadata:
```
Name = RemoveRed
Version = 1.0.0
Author = shawtymon <shawtymon@protonmail.com>
Desc = Provides a removeRed function, which removes red from a pixel.
```

Extensions would be loaded usig require:
```
var RedRemove = require('removeRed');

function effect(x, y, pixel) {
    return RedRemove.removeRed(pixel);
}
```

**Comment by QeaML** [comment]
This has been added in commit [dbd4290](https://github.com/QeaML/ximfect/commit/dbd429017f1a774df260d2db784a7c520be00ef1).
